const $=(s,p=document)=>p.querySelector(s),$$=(s,p=document)=>[...p.querySelectorAll(s)];
$$(".card").forEach((card,index)=>{const icon=document.createElement("span");icon.className="module-icon";icon.setAttribute("aria-hidden","true");icon.textContent=["✦","◌","↗","◆","◈","●"][index%6];card.prepend(icon)});
$$(".accordion-button").forEach(button=>button.onclick=()=>{const item=button.closest(".accordion-item"),open=item.classList.toggle("open");button.setAttribute("aria-expanded",open);button.lastElementChild.textContent=open?"−":"+"});
const wireFlow=flow=>{if(!flow)return;const answers=$$(".choice",flow),feedback=$(".feedback",flow),reset=$(".reset",flow);answers.forEach(answer=>answer.onclick=()=>{answers.forEach(item=>item.disabled=true);answer.classList.add(answer.dataset.answer);feedback.innerHTML=answer.dataset.feedback;feedback.classList.add("show");reset.classList.add("show")});reset?.addEventListener("click",()=>{answers.forEach(answer=>{answer.disabled=false;answer.classList.remove("correct","caution","wrong")});feedback.classList.remove("show");reset.classList.remove("show")})};
$$("[data-flow]").forEach(wireFlow);
$$("[data-xp]").forEach(box=>{const button=$("button",box),label=$("[data-xp-label]",box),bar=$(".xp-bar i",box);button?.addEventListener("click",()=>{const next=Math.min(+box.dataset.xp+15,100);box.dataset.xp=next;bar.style.width=next+"%";label.textContent=next===100?"Level up! New accessory unlocked.":next+" XP toward your next reward";button.textContent=next===100?"Unlocked":"Practice again"})});
if(location.pathname.endsWith("teens.html")){const apps=$("#apps .grid");if(apps){apps.insertAdjacentHTML("afterend",`<div class="accordion" id="danger-cards"><div class="accordion-item"><button class="accordion-button">Instagram: a perfect-looking account wants to “collab” <span>+</span></button><div class="accordion-content">Check account history and engagement. Do not pay to be sponsored or send personal information to a new DM.</div></div><div class="accordion-item"><button class="accordion-button">Snapchat: a new person wants a private story or uses a streak <span>+</span></button><div class="accordion-content">A streak is not a reason to share more or keep a secret. Pause before moving the conversation.</div></div><div class="accordion-item"><button class="accordion-button">TikTok, Discord, Roblox, or YouTube pressure <span>+</span></button><div class="accordion-content">Collab requests, Nitro links, Robux offers, private servers, downloads, and creator impersonation all deserve a pause and an independent check.</div></div></div>`);$$(".accordion-button",$("#danger-cards")).forEach(button=>button.onclick=()=>{const item=button.closest(".accordion-item"),open=item.classList.toggle("open");button.lastElementChild.textContent=open?"−":"+"})}const support=$(".accordion",$("main"));support?.insertAdjacentHTML("beforebegin",`<div class="panel flow-card" data-flow><span class="tag">SUPPORT A FRIEND</span><p class="flow-question">A friend says they are scared to tell anyone. What do you say?</p><div class="choice-list"><button class="choice" data-answer="correct" data-feedback="<b>That keeps them connected.</b> Listen without blame, help save evidence if safe, and help them reach a trusted adult or 988 if they feel trapped.">“I’m with you. Let’s find someone calm to help us think through this.”</button><button class="choice" data-answer="wrong" data-feedback="<b>They need support, not isolation.</b> Keeping it secret can make pressure stronger.">“Do not tell anyone. It will probably go away.”</button></div><div class="feedback"></div><button class="reset">Try again ↻</button></div>`);wireFlow($(".flow-card[data-flow]:last-of-type"))}
if(location.pathname.endsWith("catalogue.html")){const grid=$(".section.alt .grid");if(grid){grid.insertAdjacentHTML("beforebegin",`<div class="filters"><button class="filter active" data-filter="all">All pathways</button><button class="filter" data-filter="teen">Teens</button><button class="filter" data-filter="parent">Parents</button><button class="filter" data-filter="senior">Seniors</button></div>`);$$(".card",grid).forEach((card,index)=>card.dataset.category=["teen","parent","senior"][index]);$$(".filter").forEach(button=>button.onclick=()=>{$$(".filter").forEach(item=>item.classList.remove("active"));button.classList.add("active");$$(".card",grid).forEach(card=>card.classList.toggle("hidden",button.dataset.filter!=="all"&&card.dataset.category!==button.dataset.filter))})}}
if(location.pathname.endsWith("parents.html")){const zone=$(".no-shame");zone?.insertAdjacentHTML("afterend",`<section class="container section"><span class="eyebrow">What teens wish parents understood</span><div class="carousel panel"><div class="carousel-slide active"><h3>“I need to know I will not get in trouble.”</h3><p>Lead with reassurance before questions or consequences.</p></div><div class="carousel-slide"><h3>“Please stay calm.”</h3><p>A calm first response makes early disclosure more likely.</p></div><div class="carousel-controls"><button>←</button><button>→</button></div></div></section>`);let active=0;$$(".carousel-controls button").forEach((button,index)=>button.onclick=()=>{const slides=$$(".carousel-slide");slides[active].classList.remove("active");active=(active+(index?1:-1)+slides.length)%slides.length;slides[active].classList.add("active")})}
if(location.pathname.endsWith("seniors.html"))document.body.classList.add("senior-page");
$$(".flow-card[data-flow]").filter(flow=>!flow.closest(".flow")).forEach(wireFlow);
