// ReadyOnline Master Context: Sections 4, 6-11, 13-15, and 17
(() => {
  const topics = {
    instagram: { audience: "Teen app practice", title: "Instagram: pressure and fake opportunities", reference: "ConnectSafely.org", lessons: ["A new account can look polished and still be false.", "A real brand does not need your password, code, or private photos.", "Pause when a new person asks to move the conversation."], scenario: "A new account comments on your post, then asks you to send photos privately for a paid collaboration.", choices: [{label: "Keep it public, check the account, and ask a trusted adult before sharing.", result: "safe"}, {label: "Move to private messages because the offer sounds exciting.", result: "red"}], action: "Do not send photos or information. Save the account name, then verify through an official website or a trusted adult." },
    snapchat: { audience: "Teen app practice", title: "Snapchat: streaks and disappearing pressure", reference: "ConnectSafely.org", lessons: ["A streak is not a promise you owe someone.", "A disappearing message can still be saved or shared.", "Secrecy is a red flag, even when someone is kind."], scenario: "Someone says, “Keep our streak alive. Send a snap, but do not tell anyone.”", choices: [{label: "Pause, do not send it, and talk to someone you trust.", result: "safe"}, {label: "Send it because it disappears anyway.", result: "red"}], action: "You do not owe anyone a snap. Keep evidence if you need it and ask for help early." },
    tiktok: { audience: "Teen app practice", title: "TikTok: attention and fake agencies", reference: "ConnectSafely.org", lessons: ["A flattering comment can be a way to get access.", "A real agency gives you time to verify.", "You can leave a comment or message without explaining yourself."], scenario: "A “talent scout” says they need your account details today so you do not miss a deal.", choices: [{label: "Use a known website to verify the agency before replying.", result: "safe"}, {label: "Share the details quickly so you do not miss the chance.", result: "red"}], action: "Urgency is a signal to slow down. Do not share passwords, codes, or personal details." },
    discord: { audience: "Teen app practice", title: "Discord: private channels and rank pressure", reference: "ConnectSafely.org", lessons: ["A private channel can remove the people who could help you notice pressure.", "A gift link can be a scam or a way to create obligation.", "Your place on a server is never worth sharing personal information."], scenario: "A server member says you will lose your rank unless you join a private channel now.", choices: [{label: "Stay in the shared space and check with a trusted person or moderator.", result: "safe"}, {label: "Join right away so you do not lose your role.", result: "red"}], action: "Do not download files or move to a private channel because someone pressures you." },
    roblox: { audience: "Teen app practice", title: "Roblox: gifts and private worlds", reference: "Common Sense Media", lessons: ["A gift never means you owe someone access.", "Private worlds are not a reason to ignore a gut feeling.", "Your account and personal details belong to you."], scenario: "Someone offers Robux if you meet them in a private world and keep it secret.", choices: [{label: "Say no, leave the chat, and tell a grown-up you trust.", result: "safe"}, {label: "Go to the private world to see if the gift is real.", result: "red"}], action: "Report and block when you can. Never trade privacy for virtual currency." },
    gaming: { audience: "Teen app practice", title: "Gaming: team pressure and voice chat", reference: "ConnectSafely.org", lessons: ["Team pressure can make a bad request feel normal.", "You never need to share an account to prove you are a teammate.", "A real gaming event will not require secrecy from adults."], scenario: "A teammate asks for your login so they can “help” your rank and says not to tell anyone.", choices: [{label: "Keep your login private and check with a trusted adult.", result: "safe"}, {label: "Share it so the team does not blame you.", result: "red"}], action: "Keep passwords private. Leave voice chat or report someone who pressures you." },
    other: { audience: "Teen app practice", title: "Any app: the pattern matters", reference: "NCMEC", lessons: ["The app can change. Pressure patterns stay the same.", "You do not need proof before you pause.", "A trusted adult can help you choose the next step."], scenario: "A new person is kind, but asks you to keep the conversation secret from people who care about you.", choices: [{label: "Treat secrecy as a red flag and talk to someone calm.", result: "safe"}, {label: "Ignore the secret because they are also nice.", result: "red"}], action: "Mixed signals do not cancel red flags. Screenshot, stop contact, and get support." },
    scams: { audience: "Senior practice", title: "Scams: take your time", reference: "AARP Fraud Watch Network", lessons: ["A real business gives you time to check.", "Urgency is a reason to pause.", "Use a phone number or website you already trust."], scenario: "A caller says your bank account is at risk and you must act now.", choices: [{label: "Hang up and call the number on your bank card.", result: "safe"}, {label: "Give the caller your account code to fix it quickly.", result: "red"}], action: "Do not use a number or link supplied by an unexpected caller or message." },
    romance: { audience: "Senior practice", title: "Romance fraud: connection without pressure", reference: "AARP Fraud Watch Network", lessons: ["Wanting connection is human and good.", "Real connection does not need secrecy or money.", "A new relationship should not rush you."], scenario: "Someone you met online asks for money and says you must keep the relationship private.", choices: [{label: "Pause and talk to someone you trust before sending anything.", result: "safe"}, {label: "Send the money because they sound caring.", result: "red"}], action: "Do not send money, gift cards, or account information to an online connection." },
    "tech-support": { audience: "Senior practice", title: "Tech support fraud: use your own route", reference: "FBI IC3", lessons: ["A pop-up does not know your device is in danger.", "A real company does not ask for remote access from an unexpected message.", "Close the window and use a known support channel."], scenario: "A pop-up says your computer is infected and gives a phone number to call.", choices: [{label: "Close the pop-up and contact support through the official website.", result: "safe"}, {label: "Call the pop-up number so they can repair it.", result: "red"}], action: "Never give remote access to someone who contacted you unexpectedly." },
    phishing: { audience: "Senior practice", title: "Phishing: check before you click", reference: "FBI IC3", lessons: ["A sender name can be copied.", "A link can lead somewhere different than it appears.", "Use the company app or type the address yourself."], scenario: "A package message says you need to pay a small fee using its link.", choices: [{label: "Open the delivery company website yourself to check.", result: "safe"}, {label: "Use the message link because the fee is small.", result: "red"}], action: "Unexpected links do not get to choose where you log in or pay." },
    social: { audience: "Senior practice", title: "Social media: protect your space", reference: "AARP Fraud Watch Network", lessons: ["A profile can pretend to be local or familiar.", "Friend requests can be ignored without being rude.", "Privacy settings let you choose who sees you."], scenario: "A new profile says they know your family and asks for your phone number right away.", choices: [{label: "Do not share details. Verify through a family member another way.", result: "safe"}, {label: "Share your number so they can explain.", result: "red"}], action: "Keep personal contact details private until you verify who someone is." }
  };

  const params = new URLSearchParams(location.search);
  const topic = topics[params.get("topic")] || topics.other;
  const content = document.querySelector("[data-module-content]");
  document.querySelector("[data-module-audience]").textContent = topic.audience;
  document.querySelector("[data-module-title]").textContent = topic.title;
  document.querySelector("[data-module-summary]").textContent = "Three short lessons, one practice moment, and one clear next step.";
  content.innerHTML = `<p class="reference-tag">Reference: ${topic.reference}</p><div class="lesson-list">${topic.lessons.map((lesson, index) => `<article><span>${index + 1}</span><p>${lesson}</p></article>`).join("")}</div><section class="scenario"><span class="tag">FICTIONAL PRACTICE</span><h2>Does this feel okay?</h2><p>${topic.scenario}</p><div class="scenario-choices">${topic.choices.map(choice => `<button type="button" data-scenario-result="${choice.result}">${choice.label}</button>`).join("")}</div><div class="scenario-feedback" aria-live="polite"></div></section><section class="action-step"><span class="tag">WHAT TO DO NEXT</span><p>${topic.action}</p><button class="button secondary" type="button" data-complete-module>Mark this practice complete</button></section>`;

  const renderCrisis = data => {
    const panel = document.querySelector("[data-crisis-panel]");
    panel.innerHTML = `<h2>${data.message}</h2><ul>${data.resources.map(resource => `<li><a href="${resource.href}">${resource.name}: ${resource.contact}</a></li>`).join("")}</ul>`;
  };
  fetch("data/crisis-resources.json").then(response => response.json()).then(renderCrisis).catch(() => {
    document.querySelector("[data-crisis-panel]").innerHTML = "<h2>Help is available right now.</h2><p>Please call or text 988, or call 911 if you are in immediate danger.</p>";
  });

  document.addEventListener("click", event => {
    const scenarioChoice = event.target.closest("[data-scenario-result]");
    if (scenarioChoice) {
      const result = scenarioChoice.dataset.scenarioResult;
      const feedback = document.querySelector(".scenario-feedback");
      document.querySelectorAll("[data-scenario-result]").forEach(button => button.disabled = true);
      feedback.textContent = result === "safe" ? "That keeps your choices open. You paused, checked another way, and chose support." : "This is a red flag. Stop, save evidence if it is safe, and talk to someone you trust.";
      feedback.className = `scenario-feedback is-${result}`;
    }
    if (event.target.closest("[data-complete-module]")) {
      event.target.textContent = "Completed for this session";
      event.target.disabled = true;
      document.querySelectorAll(".lesson-progress li").forEach(item => item.classList.add("is-complete"));
    }
    if (event.target.closest("[data-feedback]")) {
      event.target.closest(".feedback-mini").querySelector("p").textContent = "Thank you. Your response is not stored.";
    }
  });
})();
